mesa: bump to 7.6.1-rc1

diff --git a/mesa/mesa.SlackBuild b/mesa/mesa.SlackBuild
--- a/mesa/mesa.SlackBuild
+++ b/mesa/mesa.SlackBuild
@@ -21,8 +21,8 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PKGNAM=mesa
-# VERSION=${VERSION:-7.6}
-VERSION=$(date +"%Y%m%d")
+VERSION=${VERSION:-7.6.1-rc1}
+# VERSION=$(date +"%Y%m%d")
 ARCH=${ARCH:-x86_64}
 BUILD=${BUILD:-1}
 TAG=${TAG=_ajb}
@@ -52,30 +52,30 @@ mkdir -p $TMP $PKG
 cd $TMP
 
 # For live build:
-GIT_URL=git://anongit.freedesktop.org/git/mesa/mesa
+# GIT_URL=git://anongit.freedesktop.org/git/mesa/mesa
 
-if [ -d ${PKGNAM}/.git ]; then
-  ( cd ${PKGNAM} && git pull )  # Should be on the 7.6 branch
-else
-  git clone -b mesa_7_6_branch $GIT_URL $PKGNAM
-fi
+# if [ -d ${PKGNAM}/.git ]; then
+#   ( cd ${PKGNAM} && git pull )  # Should be on the 7.6 branch
+# else
+#   git clone -b mesa_7_6_branch $GIT_URL $PKGNAM
+# fi
 
 # Confirm checkout
-echo " "
-echo "Checkout complete (or failed miserably) - starting build..."
-sleep 3
+# echo " "
+# echo "Checkout complete (or failed miserably) - starting build..."
+# sleep 3
 
-cd $TMP/$PKGNAM
+# cd $TMP/$PKGNAM
 
 # Create the configure script
-sh autogen.sh
+# sh autogen.sh
 
 # For the release version:
-# rm -rf Mesa-${VERSION}
-# tar xvf $CWD/MesaLib-$VERSION.tar.bz2 || exit 1
-# tar xvf $CWD/MesaGLUT-$VERSION.tar.bz2 || exit 1
-# tar xvf $CWD/MesaDemos-$VERSION.tar.bz2 || exit 1
-# cd Mesa-$VERSION
+rm -rf Mesa-${VERSION}
+tar xvf $CWD/MesaLib-$VERSION.tar.bz2 || exit 1
+tar xvf $CWD/MesaGLUT-$VERSION.tar.bz2 || exit 1
+tar xvf $CWD/MesaDemos-$VERSION.tar.bz2 || exit 1
+cd Mesa-$VERSION
 
 # Make sure ownerships and permissions are sane:
 chown -R root:root .
@@ -150,4 +150,4 @@ mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n ${OUTPUT}/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
+/sbin/makepkg -l y -c n ${OUTPUT}/${PKGNAM}-7.6_rc1-${ARCH}-${BUILD}${TAG}.txz
